@API_HostAddress = http://localhost:5086

GET {{API_HostAddress}}/api/forecast/Generate/12
Accept: application/json

###

GET {{API_HostAddress}}/api/company/Generate/6
Accept: application/json

###

GET {{API_HostAddress}}/api/vacancy/Generate/3
Accept: application/json

###